/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TaskInstructions {
        "header": string;
        "markdown_url": string;
        "tab": string;
    }
    interface TaskMarkdown {
        "markdown_url": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTaskInstructionsElement extends Components.TaskInstructions, HTMLStencilElement {
    }
    var HTMLTaskInstructionsElement: {
        prototype: HTMLTaskInstructionsElement;
        new (): HTMLTaskInstructionsElement;
    };
    interface HTMLTaskMarkdownElement extends Components.TaskMarkdown, HTMLStencilElement {
    }
    var HTMLTaskMarkdownElement: {
        prototype: HTMLTaskMarkdownElement;
        new (): HTMLTaskMarkdownElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "task-instructions": HTMLTaskInstructionsElement;
        "task-markdown": HTMLTaskMarkdownElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TaskInstructions {
        "header"?: string;
        "markdown_url"?: string;
        "tab"?: string;
    }
    interface TaskMarkdown {
        "markdown_url"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "task-instructions": TaskInstructions;
        "task-markdown": TaskMarkdown;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "task-instructions": LocalJSX.TaskInstructions & JSXBase.HTMLAttributes<HTMLTaskInstructionsElement>;
            "task-markdown": LocalJSX.TaskMarkdown & JSXBase.HTMLAttributes<HTMLTaskMarkdownElement>;
        }
    }
}
